import { sql } from "drizzle-orm";
import { index, integer, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const workItems = sqliteTable(
  "work_items",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    kind: text("kind").notNull(),
    projectId: integer("project_id"),
    parentId: integer("parent_id"),
    code: text("code").notNull().default(""),
    title: text("title").notNull(),
    description: text("description").notNull().default(""),
    status: text("status").notNull().default("Đang thực hiện"),
    priority: text("priority").notNull().default("Trung bình"),
    health: text("health").notNull().default("Đúng tiến độ"),
    lifecycle: text("lifecycle").notNull().default("Đã chốt"),
    phase: text("phase").notNull().default(""),
    company: text("company").notNull().default(""),
    owner: text("owner").notNull().default(""),
    followPerson: text("follow_person").notNull().default(""),
    nextAction: text("next_action").notNull().default(""),
    followUpDate: text("follow_up_date"),
    startDate: text("start_date"),
    dueDate: text("due_date"),
    previousDeadline: text("previous_deadline"),
    changeReason: text("change_reason"),
    estimatedMonths: integer("estimated_months"),
    progress: integer("progress").notNull().default(0),
    quantityProgress: integer("quantity_progress").notNull().default(0),
    currentHolder: text("current_holder").notNull().default(""),
    holdingSince: text("holding_since"),
    contractValue: integer("contract_value").notNull().default(0),
    amount: integer("amount").notNull().default(0),
    paidAmount: integer("paid_amount").notNull().default(0),
    paymentRound: text("payment_round").notNull().default(""),
    skippedReason: text("skipped_reason"),
    skipApproved: integer("skip_approved", { mode: "boolean" }).notNull().default(false),
    imagePath: text("image_path"),
    imageTitle: text("image_title"),
    fileName: text("file_name"),
    fileUrl: text("file_url"),
    fileStorageStatus: text("file_storage_status").notNull().default("MISSING_OR_INCORRECT"),
    fileStorageNote: text("file_storage_note"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    index("idx_work_items_kind").on(table.kind),
    index("idx_work_items_project_id").on(table.projectId),
    index("idx_work_items_parent_id").on(table.parentId),
    index("idx_work_items_file_status").on(table.fileStorageStatus),
    index("idx_work_items_health").on(table.health),
    index("idx_work_items_follow_up").on(table.followUpDate),
    index("idx_work_items_due_date").on(table.dueDate),
  ],
);
